spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/weather?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect