spring:
  task:
    scheduling:
      enable: ture
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/weather?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: tqb4DU
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/weather?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: 172.17.0.3
    port: 6379
    database: 1 #指定redis数据库，启动后默认16个，编号为0-15
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
feishu:
  appid: cli_a4e09ae4d7399013
  app-secret: o9wc9JEsBA9YeP7eAxNd2boKJ2BOByYW
  robot-webhook-address: https://open.feishu.cn/open-apis/bot/v2/hook/08999382-e021-413f-87bf-37017ba7f55f
gaode:
  web-api-key: 4516693f55a712c8d8c992aaa2dd63a3